// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yujcrqaiqnxyisgrcadi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1amNycWFpcW54eWlzZ3JjYWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMDQwMzcsImV4cCI6MjA4Nzc4MDAzN30.AKSasiXbRPF-6GsLZ7hey5-FM2-fAtXh_7bOc10QG_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});